services:
  - type: web
    name: project-folder-creation
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 4 --timeout 600
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: GOOGLE_OAUTH_TOKEN_JSON
        sync: false
      - key: DEMO_PROJECTS_PARENT_ID
        sync: false
      - key: WEBHOOK_TOKEN
        sync: false
